services:
  webapp:
    image: my-swarm-app:1.0
    ports:
      - "9090:8800"
    environment:
      - APP_VERSION=1.0
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s